algoritmo "ATIVIDADE19."
var

media:real

nota_1:real

nota_2:real

inicio

Escreval("Digite nota 1")

Leia(nota_1)

Escreval("Digite nota 2")

Leia (nota_2)

media <- (nota_1 + nota_2) /2

Escreval("A media desse aluno é",media)

EScreval()

Se(media < 7)entao

Escreval("Voce foi reprovado")

Fimse

Se(media >= 7)entao

Escreval("Meus parabéns voce foi aprovado")

Fimse

fimalgoritmo