algoritmo "ATIVIDADE8"
var

distancia:real

inicio

Escreva("Digite uma distancia em metros")

Leia(distancia)

Escreval("A distancia em decametros fica",distancia/10)

Escreval("A distancia em heqctometros fica",distancia/100)

Escreval("A distancia em quilometros fica",distancia/1000)

Escreval("A distancia em decimetros fica",distancia*10)

Escreval("A distancia em centimetros fica",distancia*100)

Escreval("A distancia em milimetros fica",distancia*1000)

fimalgoritmo