algoritmo "ATIVIDADE10"

var

largura,altura,area,quantidade,litros:real

inicio

   Escreval("Qual e a altura da sua parede?:")

Leia(altura)

   Escreval("Qual e a largura da sua parede?:")

Leia(largura)

area<-(altura * largura)

   Escreval("A parede a ser pintada mede:", area ," metros")

quantidade <- altura * altura

   Escreval("Para que essa parede seja pintada serao necessarios",quantidade," litros de tinta")

fimalgoritmo