Algoritmo "prazer"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Lídia
// Data atual  : 24/5/2024
Var
// Seção de Declarações das variáveis 
            nome:  caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
       escreva("qual o seu nome")
       leia (nome)
       escreva("prazer " , nome , " seja bem vindo(a)!")

Fimalgoritmo