Algoritmo "semnome"

Var
    altura,largura,area,litros:real

Inicio
    escreva("escreva a altura da parede")
    leia (altura)
    escreva("escreva a largura da parede")
    leia(largura)
    
    //calculo
     area <- altura * largura
     
     litros<-area /2
     
     escrevaL(" a parede tem " , area ,"metros e será preciso " , litros , "litros de tinta")



Fimalgoritmo