Algoritmo "distancia"

Var
n1:real

Inicio
      escreva("escreva a distancia em metros")
      leia(n1)
      escreva ("a distancia de " , n1)
      escreva ("metros correspondentes a:")
      escrevaL (n1/1000, "km")
      escrevaL (n1/100, "cm")
      escrevaL (n1/10, "hm")
      escrevaL (n1/10, "dm")
      escrevaL (n1/100, "dam")
      escrevaL (n1/1000, "mm")

      
      

      


Fimalgoritmo