Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Lídia
// Data atual  : 24/5/2024
Var
// Seção de Declarações das variáveis 
n,antecessor,sucessor : inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreva("digite um numero ")
   leia (n)

antecessor <- n - 1
sucessor <- n + 1

escrevaL("antescessor é " ,antecessor  , " sucessor é " , sucessor  )

Fimalgoritmo