Algoritmo "exxe 58s"

Var
idade,alunos,quantidade,soma:inteiro
media:real
Inicio

enquanto ( idade <> 999) Faca

   escreva("Digite sua idade : ")
   leia(idade)
   
   
   se(idade <> 999) entao
      quantidade <- quantidade + 1
      soma <- soma + idade
      media <- soma / quantidade
         FimSe


FimEnquanto

escreval(quantidade  )
escreval (media)



Fimalgoritmo