Algoritmo "Ex15"

//15) Crie um programa que leia o número de dias trabalhados em um mês e mostre o
//salário de um funcionário, sabendo que ele trabalha 8 horas por dia e ganha R$25
//por hora trabalhada.

Var

   Dias : Real

Inicio

      Escreval("Trabalha quantos dias no mês?")
      Leia(Dias)
      
      Escreva("Ao fim de sua jornada de trabalho mensal, você receberá: R$ ", (Dias*200))

Fimalgoritmo