Algoritmo "Ex15"

//15) Crie um programa que leia o número de dias trabalhados em um mês e mostre o
//salário de um funcionário, sabendo que ele trabalha 8 horas por dia e ganha R$25
//por hora trabalhada.

Var

   dias : Real

Inicio

      Escreval("Trabalha quantos dias no mês?")
      Leia(dias)
      
      Escreva("Ao fim de sua jornada de trabalho mensal, você receberá: R$ ", (dias*200))

Fimalgoritmo
