Algoritmo "Ex3"

//3) Crie um programa que leia o nome e o salário de um funcionário, mostrando no
//final uma mensagem.

Var

   nome: Caracter
   salario: Real

Inicio

      Escreval("Qual é o seu nome? ")
      Leia(nome)
      Escreval("Informe o salário: ")
      Leia(salario)
      Escreval("Funcionário(a): ", nome, ".")
      Escreval("Salário: ", salario, ".")
      Escreval(nome, " obteve um salário de: R$", salario, " No último mês.")

Fimalgoritmo
