Algoritmo "Ex3"

//3) Crie um programa que leia o nome e o salário de um funcionário, mostrando no
//final uma mensagem.

Var

   Nome: Caracter
   Salario: Real

Inicio

      Escreval("Qual é o seu nome? ")
      Leia(Nome)
      Escreval("Informe o salário: ")
      Leia(Salario)
      Escreval("Funcionário(a): ", Nome, ".")
      Escreval("Salário: ", Salario, ".")
      Escreval(Nome, " obteve um salário de: R$", Salario, " No último mês.")

Fimalgoritmo
