Algoritmo "Ex31"


//31) [DESAFIO] Crie um jogo de JoKenPo (Pedra-Papel-Tesoura)

var

   l1, l2, l3: Real
   escolha : inteiro

inicio

      EscrevaL (" __________________________________" )
      EscrevaL ("|                                  |")
      EscrevaL ("| JoKenPo! Pedra, Papel, Tesoura!! |")
      EscrevaL ("|__________________________________|")
      EscrevaL (" ")

      EscrevaL "(Vez do Jogador N°1:)
      
      


fimalgoritmo