Algoritmo "06-GUANABARA"
//  
//  

//Aula #06 Guanabara "Creuza quer saber qual a sua idade"

var

   anoAtual, anoNasc, idade: Inteiro

inicio

      Escreva("Em que ano nós estamos? ")
      Leia(anoAtual)
      Escreva("Em que ano eu nasci?! ")
      Leia(anoNasc)
      
      idade <- ( anoAtual - anoNasc )
      
      Escreval ("Minha idade é", idade)
      
fimalgoritmo
