Algoritmo "11.4-GUANABARA"

//Aula #11.4 Guanabara "Combinações"

var

   cont1, cont2 : Inteiro

inicio

      EscrevaL (" _______________________" )
      EscrevaL ("|                       |")
      EscrevaL ("| Combinações Guanabara |")
      EscrevaL ("|_______________________|")
      EscrevaL (" ")

      Para cont1 := 1 ate 3 faca
           Para cont2 := 1 ate 3 faca
                EscrevaL(cont1, cont2)
           FimPara
      FimPara

fimalgoritmo