algoritmo "semnome"
var

largura,comprimento:real

inicio
Escreva("Digite a largura do terreno: ")
Leia(largura)
Escreva("Digite o comprimento do terreno: ")
Leia(comprimento)

area>- largura*comprimento


Se (media<=4.9)Então
 Escreva("O aluno foi reprovado")
Senão
Se (media>5)e (media<=6.9) Então
 Escreva("O aluno está de recuperação")
Senão
 Se (media>=7) Então
  Escreva("O aluno está aprovado")
  FimSe
 FimSe
FimSe
fimalgoritmo