algoritmo "91"
var
n1,n2,maior,men:inteiro
Procedimento Maior(A,B:inteiro)
inicio
   Se A > B Entao
    Escreval("O maior valor é primeiro ")
   Senao
    Se B > A Entao
    Escreval("O maior valor é o segundo ")
   Senao
    Escreval("Os dois valores são iguais")
   FimSe
   FimSe
   
FimProcedimento
inicio
Escreval("Digite o primeiro valor: ")
Leia(n1)
Escreval("Digite o segundo valor: ")
Leia(n2)

Maior(n1,n2)


fimalgoritmo