Algoritmo "Sem Nome"

Var
n1,n2, incremento, contador: inteiro

Inicio
   Escreva("Digite o primeiro Valor: ")
   Leia(n1)

   Escreva("Digite o último Valor: ")
   Leia(n2)

   Escreva("Digite o incremento: ")
   Leia(incremento)

   contador <- n1
   Enquanto contador <= n2 faca
      Escreva(contador, " ")
      contador <- contador + incremento
   FimEnquanto

   Escreval("Acabou!")
FimAlgoritmo
