(function(g){var window=this;'use strict';var B3=function(a){a.publish("cardstatechange",a.Xk()&&a.Cp()?1:0)},C3=function(a,b){var c=g.bb(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(a==null)return;a=a[d[c]]}return a},Eqb=function(a){var b=g.Vs(a);
a=g.Ys(a);return new g.Js(b.x,b.y,a.width,a.height)},Fqb=function(a,b,c){var d=d===void 0?{}:d;
var e;return e=g.nB(a,b,function(){g.oB(e);c.apply(a,arguments)},d)},F3=function(a){a=g.fb(a);
delete D3[a];g.gd(D3)&&E3&&E3.stop()},Hqb=function(){E3||(E3=new g.Cv(function(){Gqb()},20));
var a=E3;a.isActive()||a.start()},Gqb=function(){var a=g.kb();
g.Tc(D3,function(b){Iqb(b,a)});
g.gd(D3)||Hqb()},G3=function(a,b,c,d){g.Ov.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.B=a;this.N=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.K=0;this.D=null},Iqb=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);a.progress>1&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;Jqb(a,a.progress);a.progress==1?(a.j=0,F3(a),a.onFinish(),a.qs()):a.isPlaying()&&a.XM()},Jqb=function(a,b){typeof a.G==="function"&&(b=a.G(b));
a.coords=Array(a.B.length);for(var c=0;c<a.B.length;c++)a.coords[c]=(a.N[c]-a.B[c])*b+a.B[c]},Kqb=function(a,b){g.yb.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.j},H3=function(a,b,c,d,e){G3.call(this,b,c,d,e);
this.element=a},Lqb=function(a,b,c,d,e){if(b.length!=2||c.length!=2)throw Error("Start and end points must be 2D");
H3.call(this,a,b,c,d,e)},Mqb=function(a){return Math.pow(a,3)},Nqb=function(a){return 3*a*a-2*a*a*a},Oqb=function(a){g.I.call(this);
this.B=a||window;this.j=[]},I3=function(a){return a.baseUrl||null},J3=function(a,b){return g.Qt(g.ds(a,b),function(c){return!!c})},Pqb=function(a,b,c){function d(qa){var ha=qa.hovercardButton;
if(!ha)return null;ha=ha.subscribeButtonRenderer;if(!ha)return null;var ta=f(ha.unsubscribedButtonText),P=f(ha.subscribedButtonText);if(ha.subscribed){var ua=f(ha.subscriberCountWithUnsubscribeText);var y=f(ha.subscriberCountText)}else ua=f(ha.subscriberCountText),y=f(ha.subscriberCountWithSubscribeText);var Z=null;if(qa.signinEndpoint){Z=C3(qa,"signinEndpoint","webNavigationEndpointData","url");if(!Z){var cb,La;Z=(La=g.V((cb=ha.signInEndpoint)==null?void 0:cb.commandMetadata,g.u2))==null?void 0:
La.url}if(!Z)return null}return ta&&(P||Z)?{subscribed:ha.subscribed,subscribeText:ta,subscribeCount:ua,unsubscribeText:P,unsubscribeCount:y,enabled:ha.enabled,signinUrl:Z,classic:qa.useClassicSubscribeButton}:null}
function e(qa){if(qa){var ha=[],ta=qa.videoId;ta&&ha.push("v="+ta);(ta=qa.playlistId)&&ha.push("list="+ta);(qa=qa.startTimeSeconds)&&ha.push("t="+qa);return"/watch?"+ha.join("&")}}
function f(qa){if(!qa)return null;var ha=qa.simpleText;return ha?ha:qa.runs?g.ds(qa.runs,function(ta){return ta.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,t=null,u=null,w=!1,A=null,C=null,F=null,H=null,L=null,N=null;if(h==="VIDEO")g.V(l,g.cF)?m=g.V(l,g.cF).url:(N=g.V(l,g.DS),m=e(N)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p=p.style==="LIVE"):r=f(b.videoDuration);else if(h==="PLAYLIST")g.V(l,g.cF)?m=g.V(l,g.cF).url:(N=g.V(l,g.DS),m=e(N)),n=!1,q=a,t=f(b.playlistLength);else if(h===
"CHANNEL"){if(w=C3(l,"browseEndpoint","browseId"))u=w,m="/channel/"+u;n=!1;q="new";(w=!!b.isSubscribe)?A=d(b):C=f(b.subscribersText)}else h==="WEBSITE"?((F=C3(l,"urlEndpoint","url"))&&(m=F),n=!0,q="new",F=b.icon.thumbnails[0].url):h==="CREATOR_MERCHANDISE"&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(L=f(b.additionalFeesText)),(n=C3(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=C3(b,"title","accessibility","accessibilityData","label");var R=b.endpoint?b.endpoint.clickTrackingParams:
null,da="";if(b.metadata){var na=f(b.metadata);na&&(da=na)}return{id:"element-"+c,type:h,title:f(b.title),metadata:da,callToAction:f(b.callToAction),FX:b.image,iconUrl:F,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,uF:p,playlistLength:t,channelId:u,subscribeButton:A,subscribersText:C,isSubscribe:w,targetUrl:m||null,p$:n,sessionData:R?{itct:R}:null,Lea:q,TD:a?a:null,
isPlaceholder:b.isPlaceholder,impressionUrls:J3(b.impressionUrls||[],I3),e$:J3(b.hovercardShowUrls||[],I3),clickUrls:J3(l.loggingUrls||[],I3),visualElement:g.gE(b.trackingParams),productPrice:H,additionalFeesText:L,watchEndpoint:N||null}},Qqb=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:J3(a.impressionUrls||[],I3),elements:J3(a.elements||[],function(d,e){return Pqb(b,d,e)})};
a.trackingParams&&(c.visualElement=g.gE(a.trackingParams));return c},Rqb=function(a){g.fV.call(this,a);
this.C=this.endscreen=null;this.j={};this.G={};this.D=this.B=null;this.N=[];this.Y=!0;this.K=0;a=a.U();this.Z=g.rR(a)||g.tR(a);this.events=new g.MJ(this);g.M(this,this.events);this.events.T(this.player,g.UI("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.VI("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.kc);this.events.T(window,"focus",this.Rca);this.load();var b=g.Bf("STYLE");(g.of("HEAD")[0]||document.body).appendChild(b);this.addOnDisposeCallback(function(){g.Mf(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},Sqb=function(a){return a.player.getVideoData().Hf?"current":a.Z?"new":"current"},K3=function(a){return a.player.U().playerStyle==="creator-endscreen-editor"},Tqb=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",onFinish:function(e){var f=a.C=null;e.status===200&&(e=e.responseText,e.substring(0,3)===")]}"&&(e=e.substring(3),f=JSON.parse(e),f=Qqb(f,Sqb(a))));L3(a,f)},
urlParams:{v:c},withCredentials:!0};a.Z&&(c.urlParams.ptype="embedded");var d=b.dw;d&&(c.postParams={ad_tracking:d});if(b=g.$Xa(b))if(b=g.je(b),b=g.de(b))a.C=g.GA(b,c)},L3=function(a,b,c){c=c===void 0?!0:c;
a.player.qf("creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.v(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.G={};a.N.length>0&&(a.N.forEach(function(l){l.dispose()}),a.N.length=0);
a.K=0;if((a.endscreen=b)&&b.elements){c&&Uqb(a);c=[];d=new g.TI(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.U().B||(a.B=new g.W({I:"div",S:"ytp-ce-shadow"}),g.GT(a.player,a.B.element,4),a.D=new g.qF(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=Vqb(a,e);if(f){a.j[e.id]=f;a.G[e.id]=e;g.GT(a.player,f.element,4);var h=new g.TI(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);Wqb(a,f,e)}else g.mE(new g.EB("buildEndscreenElement null",
e))}a.player.lf(c);a.kc()}},Uqb=function(a){var b=g.hE(),c=g.iE();
c&&b&&a.endscreen.visualElement&&g.mA(g.vE)(void 0,c,b,a.endscreen.visualElement)},Vqb=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={I:"div",La:["ytp-ce-element","ytp-ce-video"],W:{tabindex:"0","aria-label":b.TD||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",W:M3(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",W:{href:N3(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",La:["ytp-ce-video-title","ytp-webkit-ellipsis"],W:{dir:g.Rv(b.title||"")},xa:b.title},{I:"div",S:b.uF?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
xa:b.videoDuration||void 0}]}]};c=new g.W(a);break;case "PLAYLIST":a={I:"div",La:["ytp-ce-element","ytp-ce-playlist"],W:{tabindex:"0","aria-label":b.TD||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",W:M3(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",W:{href:N3(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",La:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],W:{dir:g.Rv(b.title||"")},xa:b.title},{I:"div",S:"ytp-ce-playlist-count",
V:[{I:"div",S:"ytp-ce-playlist-icon"},{I:"div",S:"ytp-ce-playlist-count-text",xa:b.playlistLength||void 0}]}]}]};c=new g.W(a);break;case "CHANNEL":c={I:"div",La:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],W:{tabindex:"0","aria-label":b.TD||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"a",La:["ytp-ce-channel-title","ytp-ce-link"],W:{href:N3(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Rv(b.title||"")},xa:b.title},b.subscribeButton?{I:"div",S:"ytp-ce-subscribe-container",V:[{I:"div",S:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",S:"ytp-ce-channel-subscribers-text",xa:b.subscribersText}:"",b.metadata?{I:"div",La:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],xa:b.metadata}:""]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",W:M3(b)}]};c=new g.W(c);var d=g.pf(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.Jv(d,"ytp-ce-subscribe-button");if(a.player.U().B){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.WV(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player,!1);d.appendChild(e.element);a.N.push(e)}break;case "WEBSITE":a={I:"div",La:["ytp-ce-element","ytp-ce-website"],W:{tabindex:"0","aria-label":b.TD||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",
S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-website-title",W:{dir:g.Rv(b.title||"")},xa:b.title},{I:"div",S:"ytp-ce-website-metadata",xa:b.metadata},{I:"a",La:["ytp-ce-website-goto","ytp-ce-link"],W:{href:N3(a,b.targetUrl),target:"_blank",tabindex:"-1"},xa:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",W:M3(b)},{I:"div",S:"ytp-ce-expanding-icon",W:Xqb(b.iconUrl)}]};c=new g.W(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={I:"div",S:"ytp-ce-merchandise-price-container",
V:[{I:"div",S:"ytp-ce-merchandise-price",xa:b.productPrice}]},b.additionalFeesText&&c.V.push({I:"div",S:"ytp-ce-merchandise-additional-fees",xa:b.additionalFeesText})),a={I:"div",La:["ytp-ce-element","ytp-ce-merchandise"],W:{tabindex:"0","aria-label":b.TD||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-merchandise-title",W:{dir:g.Rv(b.title||"")},xa:b.title},c,{I:"div",S:"ytp-ce-merchandise-metadata",xa:b.metadata},{I:"a",La:["ytp-ce-merchandise-goto","ytp-ce-link"],W:{href:N3(a,b.targetUrl),target:"_blank",tabindex:"-1"},xa:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",W:M3(b)},{I:"div",S:"ytp-ce-merchandise-invideo-cta-container",V:[{I:"div",S:"ytp-ce-merchandise-invideo-cta",
xa:b.callToAction||void 0}]}]},c=new g.W(a)}b.isPlaceholder&&g.Jv(c.element,"ytp-ce-placeholder");return c},M3=function(a){if(a.FX)var b=a.FX.thumbnails;
return Xqb(b?b[b.length-1].url:null)},Xqb=function(a){return a?{style:"background-image: url("+a+")"}:{}},Wqb=function(a,b,c){function d(m){m&&(b.listen("blur",function(){m.style.display!="none"&&a.Y&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.K+=m;a.K>0?(g.Jv(b.element,"ytp-ce-force-expand"),O3(a,c.id,!0)):(g.Lv(b.element,"ytp-ce-force-expand"),g.Lv(b.element,"ytp-ce-element-hover"),O3(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.listen("mouseenter",function(){Yqb(a,b,c)});
b.listen("mouseleave",function(){Zqb(a,b,c)});
a.player.U().B||b.listen("click",function(){g.Jv(b.element,"ytp-ce-element-hover")});
b.listen("click",function(m){$qb(a,c,m)});
b.listen("keypress",function(m){$qb(a,c,m)});
b.listen("focus",function(){Yqb(a,b,c)});
b.listen("blur",function(){Zqb(a,b,c)});
b.listen("touchstart",function(){Yqb(a,b,c)});
var l=g.wf("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m.stopPropagation();g.Lv(b.element,"ytp-ce-element-hover");g.Lv(b.element,"ytp-ce-force-expand")});
b.listen("keydown",function(m){a.Y=m.keyCode===9&&!m.shiftKey});
d(g.wf("ytp-sb-subscribe",b.element));d(g.wf("ytp-sb-unsubscribe",b.element));b.listen("focus",f);b.listen("blur",h)},$qb=function(a,b,c){if(b.targetUrl&&(!c||c.type!=="keypress"||c.keyCode===13)){for(var d=c.target;d&&!g.Iv(d,"ytp-ce-element");){g.Iv(d,"subscribe-label")&&arb(a,b);
if(g.Iv(d,"ytp-ce-channel-subscribe"))return;d=g.Nf(d)}if(!d||g.Iv(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])Zqb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||b.Lea==="new")arb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.je(N3(a,b.targetUrl)),c=g.de(c),g.TF(c,void 0,b.sessionData);else{var e=g.DR(a.player.U())||a.player.getVideoData().Hf,f=function(){var h=N3(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.rA(h);e&&n&&
(n.v||n.list)?a.player.ip(n.v,l,n.list,!1,void 0,m||void 0):g.Eza(h,l)};
arb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},N3=function(a,b){a=a.player.U();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.KR(a)+b}else return"";return b},Yqb=function(a,b,c){g.Iv(b.element,"ytp-ce-element-hover")||(c.type==="VIDEO"||c.type==="PLAYLIST"?g.Jv(b.element,"ytp-ce-element-hover"):a.player.U().B?(new g.Cv(function(){g.Jv(b.element,"ytp-ce-element-hover")},200)).start():g.Jv(b.element,"ytp-ce-element-hover"),P3(a,c.e$),O3(a,c.id,!0))},Zqb=function(a,b,c){g.Lv(b.element,"ytp-ce-element-hover");
g.Lv(b.element,"ytp-ce-force-expand");O3(a,c.id,!1)},O3=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.v(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.Nv(a.j[e].element,"ytp-ce-element-shadow-show",c)},P3=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||b.length===0||K3(a))c&&c();else{b=brb(a,b);var e=0,f=!1,h=new g.Cv(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.bD(b[a],d)}},arb=function(a,b,c){P3(a,b.clickUrls,c);
(a=g.iE())&&b.p$&&g.CE(a,b.visualElement)},brb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(crb(b[d],c));return a},crb=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},drb=function(a){return typeof a==="string"?a:""},Q3=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},erb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},R3=function(a){return a.value?a.value:null},S3=function(a){if(!a)return null;
var b=g.je(drb(a.value));b=g.de(b);if(!b)return null;var c=Q3(a.target,frb,"current");if(c==null)a=null;else{var d=a.show_link_icon;a=new erb(b,c,d==="true"||d==="false"?d==="true":!0,a.pause_on_navigation!=null?a.pause_on_navigation:!0)}return a},grb=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},jrb=function(a){if(!a)return null;
var b=Q3(a.type,hrb),c=Q3(a.trigger,irb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=S3(a?a:null);return b?new grb(b,c,a):null},krb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},lrb=function(a,b){return g.Cb(a.action,b)},mrb=function(a,b){this.context=a;
this.j=b},nrb=function(a){return a.customMessage?T3("div","iv-card-message",a.customMessage):""},U3=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{I:"div",S:"iv-card-image",W:{style:a},V:c}},orb=function(a){if(!a.metaInfo||a.metaInfo.length===0)return"";
var b=[];a=g.v(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(T3("li","",c.value));return{I:"ul",S:"iv-card-meta-info",V:b}},T3=function(a,b,c){b?typeof b==="string"?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Rv(c);return{I:a,W:b,xa:c}},prb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.eE&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.eE+");");c.dir=g.Rv(a.customMessage);var d=[{I:"span",xa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({I:"span",S:"iv-card-link-icon"}));return{I:"div",La:b,W:c,V:d}},V3=function(a,b,c,d){if(d){b=g.v(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.jj.click,5)}},qrb=function(a,b){this.merchant=a;
this.price=b},rrb=function(a){var b;
(b=a)&&!(b=a.length>1?a.charAt(0)==="/"&&a.charAt(1)!=="/":a==="/")&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||b.length<1||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b=b[0]==="com"&&b[1]==="youtube"||b[0]==="be"&&b[1]==="youtu");return b?a.indexOf("/redirect?")===-1:!1},srb=function(a,b){return b?b:rrb(a)?"current":"new"},W3=function(a,b){g.I.call(this);
var c=this;this.element=a;this.context=b;this.rb=!1;this.Xa=new Map;this.eb=new Map;this.context.J.addEventListener(g.UI("annotations_module"),function(d){(d=c.Xa.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.VI("annotations_module"),function(d){(d=c.eb.get(d))&&d.apply(c)})},X3=function(a,b,c,d,e,f,h){a.context.j.listen(b,"click",function(l){a.YM(c,d,e,f||[],h||0,l)});
a.context.j.listen(b,"touchstart",function(){a.rb=!1});
a.context.j.listen(b,"touchmove",function(){a.rb=!0})},trb=function(a){var b;
return((b=g.V(a,g.cF))==null?0:b.url)?g.V(a,g.cF).url:(a=g.V(a,g.DS))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},Y3=function(a,b,c){return{gZ:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
E2:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
sM:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},urb=function(a,b,c){W3.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.Ab=this.Oa=this.Lb=this.C=this.isInitialized=!1;this.cards=[];this.Cb=this.Z=this.Ma=this.G=this.Wa=this.j=null;this.ra=[];this.va=this.N=this.Ef=this.Ga=null;this.K=0;this.Ha=new g.Cv(function(){},c.X.Sk?4E3:3E3);
g.M(this,this.Ha);this.ib=new g.Cv(function(){});
g.M(this,this.ib);this.Da=new mrb(c,function(e,f,h,l,m,n){X3(d,e,f,h,l,m,n)});
this.Y=new g.W({I:"div",S:"iv-drawer",W:{id:"iv-drawer"},V:[{I:"div",S:"iv-drawer-header",W:{"aria-role":"heading"},V:[{I:"span",S:"iv-drawer-header-text"},{I:"button",La:["iv-drawer-close-button","ytp-button"],W:{"aria-label":"Ocultar cards",tabindex:"0"}}]},{I:"div",S:"iv-drawer-content"}]});g.M(this,this.Y);this.D=this.Y.element;this.Ya=new g.qF(this.Y,330);g.M(this,this.Ya);this.Kb=g.wf("iv-drawer-header-text",this.D);this.B=g.wf("iv-drawer-content",this.D);this.addCueRange(0,c.videoData.lengthSeconds*
1E3,"",function(){d.Lb&&Z3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Lb=d.C)&&$3(d)});
this.Sa=new g.MJ(this);g.M(this,this.Sa);this.J.addEventListener("videodatachange",this.Wt.bind(this))},vrb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){Z3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){$3(a)});
var c=b.headerText;g.Pf(a.Kb,c);a.Z&&a.Z.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ga=g.gE(b.trackingParams);a.N=g.gE(b.closeTrackingParams);a.Ef=g.gE(b.iconTrackingParams)},wrb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.K,d=a.J.U().experiments.gb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.QE(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,jj:{},Fp:null,Pj:e.trackingParams?g.gE(e.trackingParams):null,Ef:f&&f.trackingParams?g.gE(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
eE:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};a4(a,b)}else{var h;if((h=b.content)==null?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=(e=b.content)==null?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.QE(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:b4(a,c,b,f),sponsored:!1,jj:Y3(f,e,f.command),Fp:f.trackingParams?g.gE(f.trackingParams):null,Pj:e.trackingParams?g.gE(e.trackingParams):null,Ef:l&&l.trackingParams?g.gE(l.trackingParams):null,imageUrl:c4(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.QE(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,eE:null,title:f.title?g.QE(f.title):"",customMessage:f.callToAction?g.QE(f.callToAction):"",url:g.V(f.command,g.cF).url?S3({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.V(f.command,g.cF).url}):null,onClickCommand:null};a4(a,b)}else{var m;if((m=b.content)==null?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=(f=b.content)==null?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"collaborator",teaserText:g.QE(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:b4(a,c,b,e),sponsored:!1,jj:Y3(e,f,e.endpoint),Fp:e.trackingParams?g.gE(e.trackingParams):null,Pj:f.trackingParams?g.gE(f.trackingParams):null,Ef:l&&l.trackingParams?g.gE(l.trackingParams):null,channelId:g.V(e.endpoint,g.SS).browseId,customMessage:e.customText?g.QE(e.customText):null,profileImageUrl:c4(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.QE(e.channelName):"",metaInfo:[e.subscriberCountText?g.QE(e.subscriberCountText):""],url:S3({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.V(e.endpoint,g.SS).canonicalBaseUrl?g.V(e.endpoint,g.SS).canonicalBaseUrl:"/channel/"+g.V(e.endpoint,g.SS).browseId}),onClickCommand:null};a4(a,b)}else{var n;if((n=b.content)==null?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=(l=b.content)==null?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"playlist",teaserText:g.QE(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:b4(a,c,b,e),sponsored:!1,jj:Y3(e,f,e.action),Fp:e.trackingParams?g.gE(e.trackingParams):null,Pj:f.trackingParams?g.gE(f.trackingParams):null,Ef:l&&l.trackingParams?g.gE(l.trackingParams):null,GH:c4(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.QE(e.customMessage):null,playlistVideoCount:g.QE(e.playlistVideoCount),title:e.playlistTitle?g.QE(e.playlistTitle):"",metaInfo:[e.channelName?g.QE(e.channelName):
"",e.videoCountText?g.QE(e.videoCountText):""],url:S3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:trb(e.action)}),onClickCommand:null};a4(a,b)}else{var p;if((p=b.content)==null?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=(q=b.content)==null?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"video",teaserText:g.QE(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:b4(a,c,b,e),sponsored:!1,jj:Y3(e,f,e.action),Fp:e.trackingParams?g.gE(e.trackingParams):null,Pj:f.trackingParams?g.gE(f.trackingParams):null,Ef:l&&l.trackingParams?g.gE(l.trackingParams):null,GH:c4(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.QE(e.lengthString):null,customMessage:e.customMessage?g.QE(e.customMessage):null,title:e.videoTitle?g.QE(e.videoTitle):"",metaInfo:[e.channelName?g.QE(e.channelName):
"",e.viewCountText?g.QE(e.viewCountText):""],isLiveNow:!!e.badge,url:S3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:trb(e.action)}),onClickCommand:null};a4(a,b)}}}}}a.K++},c4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||a[e].width===290)return a[e];
((a[e].height||0)<b||(a[e].width||0)<290)&&(c<0||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||(a[e].width||0)>=290)&&(d<0||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[d>=0?d:c]},b4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},yrb=function(a,b){if(b=xrb(a,b))b===a.j&&(a.j=null),a.J.removeCueRange(b.xf.id),g.Mf(b.rO),g.Gb(a.cards,b),a.JI(),d4(a)},Z3=function(a,b,c){if(!a.C){a.Ya.show();
a.Wa=new g.Cv(function(){g.Jv(a.context.J.getRootNode(),g.zY.IV_DRAWER_OPEN)},0);
a.Wa.start();a.Sa.T(a.B,"mousewheel",function(h){a.Ha.start();h.preventDefault();h=h||window.event;var l=0;h.type=="MozMousePixelScroll"?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=h.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.iE();d&&a.Ga&&a.N&&g.AE(d,[a.Ga,a.N]);b={TRIGGER_TYPE:b};for(var e=g.v(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.f_||(f.f_=!0,zrb(a.context.logger,f.xf.jj.gZ,b)),d&&g.AE(d,[f.xf.Fp]);B3(a.J);c&&(a.G=new g.Cv(function(){a.Ma=a.Z;a.Cb.focus()},330),a.G.start())}},$3=function(a){a.C&&(a.Ya.hide(),g.tB(a.Sa),g.Lv(a.context.J.getRootNode(),g.zY.IV_DRAWER_OPEN),a.C=!1,B3(a.J),a.G&&a.G.stop(),a.G=new g.Cv(function(){a.Ma&&(a.Ma.focus(),a.Ma=null)},330),a.G.start())},Arb=function(a){g.Kv(a.Jb(),
[g.zY.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.GT(a.J,a.D,5);a.vI();a.Z=g.wf("ytp-cards-button",a.J.getRootNode());a.Cb=g.wf("iv-drawer-close-button",a.D);a.isInitialized=!0},Brb=function(a){a.ra.push(g.pD("iv-teaser-shown",a.e5,a));
a.ra.push(g.pD("iv-teaser-hidden",a.J$,a));a.ra.push(g.pD("iv-teaser-clicked",a.d5,a));a.Ab=!0},Crb=function(a,b){var c;
return b.onClickCommand&&((c=g.V(b.onClickCommand,g.bnb))==null?void 0:c.targetId)==="engagement-panel-error-corrections"?(a.va=b,!0):!1},Drb=function(a,b){a.va=b;
var c=a.J.getVideoData();if(!c)return!1;c=g.xWa(c);if(c==null?0:c.markersMap)for(var d,e=0;((d=c)==null?void 0:d.markersMap.length)>e;e++){var f=void 0,h=(f=c)==null?void 0:f.markersMap[e];if(h.key==="ERROR_CORRECTION_MARKERS"&&(f=void 0,(h=(f=h.value)==null?void 0:f.markers)&&h.length>0))return d=void 0,b.startMs=((d=g.V(h[0],g.$3a))==null?void 0:d.timeRangeStartMillis)||0,a.va=null,!0}return!1},a4=function(a,b){if(!Crb(a,b)||Drb(a,b)){var c=Erb(a,b);
if(c){var d={xf:b,rO:c.element,f_:!1};if(b.onClickCommand)a.J.L("web_infocards_teaser_show_logging_fix")&&(a.Ab||Brb(a),yrb(a,b.id),c=a.findLastIndex(d),g.Nb(a.cards,c,0,d));else{a.isInitialized||Arb(a);yrb(a,b.id);var e=a.findLastIndex(d);g.Nb(a.cards,e,0,d);c.Ka(a.B,e);a.JI()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.j=d,d4(a),Frb(a,d),Z3(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=a.context.J.getCurrentTime()*1E3,c<5E3&&c>b.startMs&&Grb(a,d),a.addCueRange(b.startMs,
b.startMs+1,b.id,function(){Grb(a,d)}),d4(a))}}},Erb=function(a,b){switch(b.type){case "simple":a=a.Da;
var c=b.displayDomain?{I:"div",S:"iv-card-image-text",xa:b.displayDomain}:void 0;var d=prb(b);c={I:"div",La:["iv-card"],V:[{I:"a",S:"iv-click-target",W:{href:b.url?R3(b.url)||"":""},V:[U3(b.imageUrl,c),{I:"div",S:"iv-card-content",V:[T3("h2",void 0,b.title),d]}]}]};c=new g.W(c);V3(a,g.vf("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Da;c={I:"div",La:["iv-card","iv-card-channel"],V:[{I:"a",La:["iv-click-target"],W:{href:R3(b.url)||"","data-ytid":b.channelId},V:[U3(b.profileImageUrl),
{I:"div",S:"iv-card-content",V:[nrb(b),{I:"h2",S:"iv-card-primary-link",xa:b.title},orb(b)]}]}]};c=new g.W(c);V3(a,g.vf("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Da;c={I:"div",La:["iv-card","iv-card-playlist"],V:[{I:"a",S:"iv-click-target",W:{href:R3(b.url)||""},V:[U3(b.GH,{I:"div",S:"iv-card-image-overlay",V:[{I:"span",S:"iv-card-playlist-video-count",xa:b.playlistVideoCount}]}),{I:"div",S:"iv-card-content",V:[nrb(b),T3("h2","iv-card-primary-link",b.title),orb(b)]}]}]};
c=new g.W(c);V3(a,g.vf("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Da;var e=b.offers.length!=0;c=["iv-card"];d="";var f=prb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({I:"div",S:"iv-card-offer-price",xa:f.price}),f.merchant&&e.push({I:"div",S:"iv-card-offer-merchant",xa:f.merchant}),f={I:"div",V:e});e=b.url?R3(b.url)||"":"";c={I:"div",La:c,W:{tabindex:"0"},V:[{I:"a",La:["iv-card-image","iv-click-target"],W:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{I:"div",S:"iv-card-content",V:[b.sponsored?{I:"div",S:"iv-card-sponsored",V:["Patrocinado",{I:"div",S:"iv-ad-info-container",V:[{I:"div",S:"iv-ad-info",xa:"{{adInfo}}"},{I:"div",S:"iv-ad-info-icon-container",V:[{I:"div",S:"iv-ad-info-icon"},{I:"div",S:"iv-ad-info-callout"}]}]}]}:"",{I:"a",S:"iv-click-target",W:{href:e},V:[T3("h2",d,b.title),f]}]}]};c=new g.W(c);d=g.Bf("span");g.Pf(d,"Voc\u00ea v\u00ea este produto porque achamos que ele \u00e9 relevante para o v\u00eddeo. O Google pode ser compensado pelo comerciante.");
c.Dd(d,"adInfo");V3(a,g.vf("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Da;d=b.videoDuration?{I:"span",S:"iv-card-video-duration",xa:b.videoDuration}:void 0;f=b.isLiveNow?{I:"span",La:["yt-badge","yt-badge-live"],xa:"AO VIVO AGORA"}:null;e={I:"div",La:["iv-card","iv-card-video"],V:[{I:"a",S:"iv-click-target",W:{href:((c=b.url)==null?void 0:R3(c))||""},V:[U3(b.GH,d),{I:"div",S:"iv-card-content",V:[nrb(b),T3("h2","iv-card-primary-link",b.title),orb(b),f]}]}]};c=new g.W(e);V3(a,g.vf("iv-click-target",
c.element),b,b.url);b=c;break;default:return null}return b},Hrb=function(a){if(a.j)return a.j.xf.type==="productListing";
if(a.J.L("enable_wn_infocards")){var b;return!((b=a.cards)==null||!b.length)&&g.es(a.cards,function(c){return c.xf.type==="productListing"})}return g.es(a.cards,function(c){return c.xf.type==="productListing"})},d4=function(a){g.Nv(a.J.getRootNode(),"ytp-cards-shopping-active",Hrb(a))},Grb=function(a,b){if(!g.Iv(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.iE(),d=a.j?a.j.xf.Ef:a.Ef;
c&&d&&g.BE(c,[d]);a.j=b;d4(a)}(c=a.isInitialized&&a.Jb().style.display=="none")||(c=a.context.J.getPlayerState(),d=c===0&&a.context.J.getCurrentTime()===0,c=!(c===1||c===3||d));c||b.xf.teaserDurationMs&&a.J.hC(!0,{teaserText:b.xf.teaserText,durationMs:b.xf.teaserDurationMs,onClickCommand:b.xf.onClickCommand});a.ib.isActive()||((!a.C||!a.Ha.isActive()&&a.Oa)&&Frb(a,b),a.ib.start(910+b.xf.teaserDurationMs))}},Frb=function(a,b){a.Y.Ib?(b=new G3([0,
a.B.scrollTop],[0,b.rO.offsetTop],600,Nqb),a.context.C.listen(b,"animate",function(c){a.B.scrollTop=c.y}),a.context.C.listen(b,"finish",function(c){a.B.scrollTop=c.y}),b.play()):(g.ME(a.Y,!0),a.B.scrollTop=b.rO.offsetTop,g.ME(a.Y,!1))},e4=function(a){return a.j&&a.j.xf?a.j.xf:a.cards[0]&&a.cards[0].xf?a.cards[0].xf:null},xrb=function(a,b){return g.Cb(a.cards,function(c){return c.xf.id===b})},f4=function(a,b,c){W3.call(this,a,b);
this.annotation=c;this.isActive=!1},Irb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},g4=function(a,b,c){f4.call(this,a,b,c);
this.B=null;this.N=!1;this.C=null;this.D=!1;this.j=this.K=this.G=null},Jrb=function(a,b){var c=c===void 0?0:c;
var d=Eqb(b).width;g.Ts(b,d);c=new Lqb(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,Mqb);g.M(a,c);a.context.C.listen(c,"begin",function(){g.Zs(b,!0)});
c.play()},Mrb=function(a,b){if(b.channel_name){var c=a.createElement({I:"div",
La:["iv-branding-context-name"],xa:b.channel_name}),d=a.createElement({I:"div",La:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.WV(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.J,!1),a.j.Ka(d));var f=a.createElement({I:"div",La:["iv-branding-context-subscribe-caret"]}),h=a.createElement({I:"div",La:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.Zs(h,!1);var l=a.createElement({I:"div",La:["branding-context-container-outer"]});l.appendChild(h);g.Ms(l,"right",b.image_width+"px");g.Ff(a.Jb(),l);a.C=new g.Cv(function(){Krb(a,h,l)},500);
g.M(a,a.C);a.context.j.listen(a.Jb(),"mouseover",function(){Lrb(a,h,l,f,b.image_height)});
a.context.j.listen(a.Jb(),"mouseout",function(){a.C.start()})}},Lrb=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.Ys(b);a.j||(b.style.width=g.Ss(f.width,!0),c.style.width=g.Ss(f.width,!0));g.Ms(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Ms(d,"right","1px");a.D=!0;g.Zs(b,!0);a.G=new g.Cv(function(){g.Jv(this.Jb(),"iv-branding-active")},0,a);
a.G.start()}},Krb=function(a,b,c){g.Lv(a.Jb(),"iv-branding-active");
a.K=new g.Cv(function(){g.Zs(b,!1);a.j||(c.style.width=g.Ss(0,!0))},250);
a.K.start();a.D=!1},Nrb=function(a,b,c,d,e,f,h){this.j=a;
this.C=b;this.X=c;this.videoData=d;this.logger=e;this.J=f;this.B=h},Orb=function(a,b,c){f4.call(this,a,b,c);
var d=this;this.Z=this.isCollapsed=this.Y=!1;this.K=5E3;this.B=this.C=this.j=this.D=null;this.N=this.createElement({I:"div",La:["iv-promo-contents"]});this.G=new g.Cv(function(){d.j.setAttribute("aria-hidden","true");g.Zs(d.C,!1);g.Zs(d.B,!0)},700,this);
g.M(this,this.G)},Rrb=function(a,b,c){c.stopPropagation();
Prb(a);Qrb(a,b);a.j.focus()},Srb=function(a){a.isCollapsed||a.Z||a.D||(g.Jv(a.Jb(),"iv-promo-collapsed"),a.isCollapsed=!0,a.G.start())},Prb=function(a){a.G.stop();
a.isCollapsed&&(g.Mv(a.Jb(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Zs(a.B,!1),g.Zs(a.C,!0))},Qrb=function(a,b){a.D||(a.D=g.ng(function(){Trb(this);
Srb(this)},b,a))},Trb=function(a){a.D&&(g.Ua.clearTimeout(a.D),a.D=null)},Urb=function(a){this.J=a},zrb=function(a,b,c){b&&(c?h4(a,b.map(function(d){return g.dv(d,c)})):h4(a,b))},h4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.v(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.bD(m,f);d&&(e++,d!==0&&a.J.sendVideoStatsEngageEvent(d,f))},Vrb=function(a){g.fV.call(this,a);
var b=this;this.ra=this.Z=!1;this.loadNumber=0;this.K={};this.logger=new Urb(this.player);this.D=new g.MJ(this);this.G=this.N=null;this.events=new g.MJ(this);this.Yg=this.Y=this.j=null;this.va=[];g.M(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.publish("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.publish("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.publish("onShowControls")});
this.D.T(this.player,"resize",function(d){b.publish("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.publish("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.f5,this);this.subscribe("resize",this.kL,this);this.player.U().Oa.subscribe("vast_info_card_add",this.w0,this);g.M(this,this.events);this.Da=this.createElement({I:"div",S:"video-custom-annotations"});this.B=new g.W({I:"div",La:["ytp-player-content","ytp-iv-player-content"]});g.M(this,this.B);g.GT(this.player,this.B.element,4);this.B.hide();this.C=new g.W({I:"div",La:["ytp-iv-video-content"]});g.M(this,this.C);a=this.createElement({I:"div",S:"video-annotations"});
a.appendChild(this.Da);this.C.element.appendChild(a);this.bv()&&this.load();var c=this.createElement({I:"style"});(g.of("HEAD")[0]||document.body).appendChild(c);this.addOnDisposeCallback(function(){g.Mf(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},Wrb=function(a){a=a.createElement({I:"div",
La:["annotation","annotation-type-custom"]});g.Zs(a,!1);return a},Xrb=function(a,b){b=!b.isCued()&&!g.xF(b,1024);
g.ME(a.B,b);g.ME(a.C,b)},Yrb=function(a,b,c){a.Z=!0;
a.G=g.GA(b,c)},Zrb=function(a,b){for(var c={},d=g.v(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.db(e)&&e.nodeType==1){if(c[e.tagName])var f=c[e.tagName];else if(e.tagName==="data"){e.childNodes.length>0&&(f=e.childNodes[0].nodeValue,c[e.tagName]=typeof f==="string"?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&e.tagName==="TEXT"?e.childNodes.length===1&&e.childNodes[0].nodeType===3?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(Zrb(a,e))}return c},csb=function(a){var b=a.player.getVideoData();
if(b.Xa){var c=a.player.U().Oa.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=a.loadNumber;f=b.videoId;a.loaded&&a.loadNumber===e&&a.player.getVideoData().videoId===f&&(h=g.zA(h)&&h.responseXML?h.responseXML:null)&&$rb(a,h)}};
g.QB()&&(d.onFinish=asb(a,d.onFinish));d.postParams={ic_only:"1"};bsb(d,c);a.Z=!0;g.GA(b.Xa,d)}}},bsb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.OI&&(a.postParams.ic_coll=b.OI);b.sO&&(a.postParams.ic_xml=b.sO);b.xM&&(a.postParams.ic_track=b.xM)},dsb=function(a){var b=new g.W({I:"div"});
g.Zs(b.element,!1);var c=new urb(a.player,b.element,i4(a));g.M(c,b);b.Ka(a.B.element);c.qH();return c},fsb=function(a,b){var c,d;
if(b=(c=b.getWatchNextResponse())==null?void 0:(d=c.cards)==null?void 0:d.cardCollectionRenderer)a.ra=!0,esb(a,b),b.headerText&&a.Yg&&(c=g.QE(b.headerText),a.Yg.setAttribute("title",c))},i4=function(a){if(!a.Y){var b=new Oqb(a);
g.M(a,b);var c=new g.Bq(a);g.M(a,c);a.Y=new Nrb(b,c,a.player.U(),a.player.getVideoData(),a.logger,a.player,a.Bj)}return a.Y},$rb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(d.length<1)&&(d=d[0].getAttribute("itct"))){var e=g.iE();if(e){var f=g.hE();f&&g.mA(g.cya)(void 0,e,f,[g.gE(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=Zrb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m=typeof h==="string"&&l!=null&&h!=null&&h.match(l)?h:"";var n=Q3(f.type,gsb),p=Q3(f.style,hsb),q=drb(f.data),r=q.length!==0?JSON.parse(q):{};var t=f.action;f=jrb;if(t==null)var u=null;else if(g.bb(t)){l=[];for(var w=g.v(t),A=w.next();!A.done;A=w.next()){var C=f(A.value);
C&&l.push(C)}u=l}else{var F=f(t);u=F?[F]:[]}e=m&&n?new krb(m,n,p,u,r):null}else e=null}catch(na){}if(e)if(e.type==="branding"||e.type==="promotion"){f=a;l=e;var H=Wrb(f),L=null;switch(l.type){case "branding":if(f.player.U().Fd)break;f.B.element.appendChild(H);L=new g4(H,i4(f),l);break;case "promotion":g.GT(f.player,H,4),L=new Orb(H,i4(f),l)}L&&L.qH();if(f=L)g.M(a,f),a.K[e.id]=f}else if(e.type==="card"||e.type==="drawer"){a.j||(a.j=dsb(a),g.M(a,a.j));if(e.type==="card"){H=a.j;var N=(c=e)&&c.data&&
c.data.card_type;e=c.data;if(N)switch(f=e.tracking||{},f={gZ:f.impression,click:f.click,close:f.close,E2:f.teaser_impression,sM:f.teaser_click},l=e.tracking_params||{},L=null,N){case "collaborator":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,jj:f,Fp:l.card?g.gE(l.card):null,Pj:l.teaser?g.gE(l.teaser):null,Ef:l.icon?g.gE(l.icon):
null,channelId:e.channel_id,customMessage:e.custom_message?e.custom_message:null,profileImageUrl:e.image_url,title:e.title,metaInfo:e.meta_info,url:S3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};a4(H,c);break;case "playlist":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,jj:f,
Fp:l.card?g.gE(l.card):null,Pj:l.teaser?g.gE(l.teaser):null,Ef:l.icon?g.gE(l.icon):null,GH:e.image_url,playlistVideoCount:e.playlist_video_count,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,url:S3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};a4(H,c);break;case "productListing":e.signin_url&&(L=S3({target:"current",value:e.signin_url}));N=[];for(var R=e.offers||[],da=0;da<R.length;da++)N.push(new qrb(g.cf(R[da].merchant),
g.cf(R[da].price)));c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,jj:f,Fp:l.card?g.gE(l.card):null,Pj:l.teaser?g.gE(l.teaser):null,Ef:l.icon?g.gE(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,eE:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?
e.custom_message:null,url:S3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),xsb:L,wsb:e.signin_title?e.signin_title:void 0,tsb:e.signin_message?e.signin_message:void 0,offers:N,onClickCommand:null};a4(H,c);break;case "simple":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,jj:f,Fp:l.card?g.gE(l.card):
null,Pj:l.teaser?g.gE(l.teaser):null,Ef:l.icon?g.gE(l.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,eE:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?e.custom_message:null,url:S3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};a4(H,c);break;case "video":c={id:c.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,
startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,jj:f,Fp:l.card?g.gE(l.card):null,Pj:l.teaser?g.gE(l.teaser):null,Ef:l.icon?g.gE(l.icon):null,GH:e.image_url,videoDuration:e.video_duration||null,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,isLiveNow:!!e.is_live_now,url:S3({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null},a4(H,c)}}else vrb(a.j,e);c=!0}}c&&
(B3(a.player),a.kL())},esb=function(a,b){var c=!1;
a.j||(a.j=dsb(a),g.M(a,a.j));for(var d=g.v(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(wrb(a.j,e.cardRenderer),c=!0);if(c){var f;(f=a.player.getVideoData())!=null&&g.ZS(f)||(c=a.j,d=b.headerText?g.QE(b.headerText):"",g.Pf(c.Kb,d),c.Z&&c.Z.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ga=b.trackingParams?g.gE(b.trackingParams):null,c.N=b.closeButton.infoCardIconRenderer.trackingParams?g.gE(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.Ef=b.icon.infoCardIconRenderer.trackingParams?g.gE(b.icon.infoCardIconRenderer.trackingParams):null,a.kL());B3(a.player)}},isb=function(a,b,c,d,e){if(!a.player.U().Fd){var f=[];
b.navigationEndpoint&&g.V(b.navigationEndpoint,g.SS)&&g.V(b.navigationEndpoint,g.SS).browseId&&f.push(new grb("openUrl","click",new erb("/channel/"+g.V(b.navigationEndpoint,g.SS).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.V(b.subscribeButton,
g.TS)){d.channel_id=g.V(b.subscribeButton,g.TS).channelId;var l;b=g.V(b.subscribeButton,g.TS);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.QE(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.QE(b.subscriberCountText))):(b.subscriberCountText&&(e=g.QE(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.QE(b.subscriberCountWithSubscribeText)));var m,n=((m=g.V((l=b.signInEndpoint)==null?void 0:l.commandMetadata,g.u2))==null?void 0:m.url)||"";l={subscribeText:g.QE(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.QE(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new krb(c,"branding","branding",f,d);l=Wrb(a);a.B.element.appendChild(l);f=new g4(l,i4(a),f);f.qH();g.M(f,f);a.K[c]=f}},asb=function(a,b){return function(){var c=g.Ja.apply(0,arguments);
a.Na()||a.va.push(g.yv.Qi(function(){b.apply(null,g.ra(c))}))}},jsb=function(a){return a==="annotation-editor"||a==="live-dashboard"};
g.zT.prototype.hC=g.ca(28,function(a,b){var c=g.EV(this.Bb());c&&c.hC(a,b)});
var D3={},E3=null;g.lb(G3,g.Ov);g.k=G3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||this.j==0)this.progress=0,this.coords=this.B;else if(this.isPlaying())return!1;F3(this);this.startTime=a=g.kb();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.cL();this.Ln("play");this.isPaused()&&this.Ln("resume");this.j=1;var b=g.fb(this);b in D3||(D3[b]=this);Hqb();Iqb(this,a);return!0};
g.k.stop=function(a){F3(this);this.j=0;a&&(this.progress=1);Jqb(this,this.progress);this.onStop();this.qs()};
g.k.pause=function(){this.isPlaying()&&(F3(this),this.j=-1,this.Ln("pause"))};
g.k.ya=function(){this.j==0||this.stop(!1);this.Ln("destroy");G3.Pf.ya.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.XM=function(){this.Ln("animate")};
g.k.Ln=function(a){this.dispatchEvent(new Kqb(a,this))};
g.lb(Kqb,g.yb);g.lb(H3,G3);H3.prototype.C=function(){};
H3.prototype.XM=function(){this.C();H3.Pf.XM.call(this)};
H3.prototype.qs=function(){this.C();H3.Pf.qs.call(this)};
H3.prototype.cL=function(){this.C();H3.Pf.cL.call(this)};
g.lb(Lqb,H3);Lqb.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.x(Oqb,g.I);g.k=Oqb.prototype;g.k.listen=function(a,b,c,d){c=(0,g.ib)(c,d||this.B);a=g.nB(a,b,c);this.j.push(a);return a};
g.k.OF=function(a,b,c,d){c=(0,g.ib)(c,d||this.B);a=Fqb(a,b,c);this.j.push(a);return a};
g.k.Oc=function(a){g.oB(a);g.Gb(this.j,a)};
g.k.removeAll=function(){g.oB(this.j);this.j.length=0};
g.k.ya=function(){this.removeAll();g.I.prototype.ya.call(this)};g.x(Rqb,g.fV);g.k=Rqb.prototype;g.k.load=function(){g.fV.prototype.load.call(this);if(!K3(this)){var a=g.aYa(this.player.getVideoData());a?(a=Qqb(a,Sqb(this)),L3(this,a,!1)):Tqb(this)}};
g.k.unload=function(){L3(this,null);this.C&&(this.C.abort(),this.C=null);g.fV.prototype.unload.call(this)};
g.k.Th=function(a,b){return K3(this)?a==="loadCustomEndscreenRenderer"?(a=Qqb(b,"new"),L3(this,a),!0):null:null};
g.k.getOptions=function(){return K3(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.kc=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&a.width!==0&&a.height!==0){var b=this.player.getPlayerSize();if(b&&b.width!==0&&b.height!==0){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<ksb.length;f++){var h=Math.abs(b.width-ksb[f]);if(e===-1||d>=h)e=f,d=h}d=lsb[e];this.B&&g.Ms(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Xs(e.element,m,f);g.Ts(e.element,n,p);g.Mv(e.element,msb);m>256||f>256?g.Jv(e.element,"ytp-ce-large-round"):m>96||f>96?g.Jv(e.element,"ytp-ce-medium-round"):g.Jv(e.element,"ytp-ce-small-round");g.Mv(e.element,nsb);m=h.left+h.width/2;h=h.top+l/2;g.Jv(e.element,m<=.5&&h<=.5?"ytp-ce-top-left-quad":m>.5&&h<=.5?"ytp-ce-top-right-quad":
m<=.5&&h>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Mv(e.element,lsb);g.Jv(e.element,d);(e=g.pf(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Ms(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if(a.getId()==="ytp-ce-in-endscreen")P3(this,this.endscreen.impressionUrls),(a=g.iE())&&this.endscreen.visualElement&&g.zE(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.G[a];g.Jv(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.Jv(b,"ytp-ce-shown");P3(this,c.impressionUrls);(b=g.iE())&&g.zE(b,c.visualElement);this.player.U().N&&this.player.jb("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if(a.getId()!=="ytp-ce-in-endscreen"){a=a.getId().substring(15);var b=this.j[a];g.Lv(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Lv(b,"ytp-ce-shown");this.player.U().N&&this.player.jb("endscreenelementhidden",a)}};
g.k.Rca=function(a){var b=this;a.target===window&&(new g.Cv(function(){for(var c=g.v(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.Mv(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var ksb=[346,426,470,506,570,640,853,1280,1920],lsb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),nsb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],msb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var frb={Vwa:"current",rYa:"new"};var hrb={CLOSE:"close",j1a:"openUrl",SUBSCRIBE:"subscribe"},irb={gva:"click",CLOSE:"close",gJa:"hidden",s7a:"rollOut",t7a:"rollOver",n9a:"shown"};krb.prototype.Ee=function(){var a=lrb(this,function(b){return b.type==="openUrl"&&b.url!=null});
return a?a.url:null};
var hsb={tpa:"anchored",W3:"branding",CHANNEL:"channel",Lwa:"cta",jJa:"highlightText",qNa:"label",PLAYLIST:"playlist",POPUP:"popup",Bbb:"speech",SUBSCRIBE:"subscribe",ofb:"title",VIDEO:"video",Wmb:"website"},gsb={W3:"branding",Isa:"card",Tya:"drawer",iJa:"highlight",ITa:"marker",C5a:"promotion",TEXT:"text",Bob:"widget"};g.x(W3,g.I);g.k=W3.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.TI(a,b,{id:c,namespace:"annotations_module"});d&&this.Xa.set(a,d);e&&this.eb.set(a,e);this.context.J.lf([a])};
g.k.qH=function(){this.context.B.subscribe("resize",this.JI,this)};
g.k.Jb=function(){return this.element};
g.k.YM=function(a,b,c,d,e,f){if(this.rb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Mf(this.Jb())};
g.k.JI=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=R3(a);if(f){var h=srb(f,a.target),l=function(){a.j&&e.context.J.pauseVideo();var m=e.context.videoData.Hf||!1,n=g.rA(f||"");m&&n&&(n.v||n.list)?e.context.J.ip(n.v,b,n.list,!1):g.TF(f||"",h==="current"?"_top":void 0,b)};
h==="new"&&(l(),l=null);h4(this.context.logger,c,l,d);rrb(f)||(c=g.iE(),d=b.itct,c&&d&&g.CE(c,g.gE(d)))}};
g.k.ya=function(){this.Xa.clear();this.eb.clear();g.I.prototype.ya.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.M(this,a);return a.element};g.x(urb,W3);g.k=urb.prototype;g.k.Wt=function(){this.va&&a4(this,this.va)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.Ys(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.JI=function(){var a=this.isAvailable();g.Zs(this.Jb(),a);g.Nv(this.context.J.getRootNode(),g.zY.IV_DRAWER_ENABLED,a);B3(this.J)};
g.k.destroy=function(){this.J.hC(!1);try{this.J.getRootNode().removeChild(this.D)}catch(a){}g.qD(this.ra);g.tB(this.Sa);this.Wa&&this.Wa.dispose();this.G&&this.G.dispose();W3.prototype.destroy.call(this)};
g.k.vI=function(){var a=this,b=g.wf("iv-drawer-close-button",this.D);this.context.j.listen(b,"click",this.Q7,this);this.context.j.listen(this.B,"touchend",function(){a.Ha.start()});
this.context.j.listen(this.B,"scroll",this.m8,this);this.context.B.subscribe("onHideControls",function(){a.Oa=!0});
this.context.B.subscribe("onShowControls",function(){a.Oa=!1});
this.context.B.subscribe("onVideoAreaChange",function(){a.Oa=g.Iv(a.J.getRootNode(),"ytp-autohide")});
this.ra.push(g.pD("iv-button-shown",this.I$,this));this.ra.push(g.pD("iv-button-hidden",this.H$,this));Brb(this)};
g.k.findLastIndex=function(a){if(this.cards.length===0)return 0;var b=g.Db(this.cards,function(c){return a.xf.startMs>c.xf.startMs||a.xf.startMs===c.xf.startMs&&a.xf.timestamp>=c.xf.timestamp?!0:!1});
return b===-1?0:b+1};
g.k.Q7=function(){if(this.C){h4(this.context.logger,e4(this).jj.close);var a=g.iE();a&&this.N&&g.CE(a,this.N);$3(this)}};
g.k.m8=function(){g.Nv(this.D,"iv-drawer-scrolled",this.B.scrollTop>0)};
g.k.I$=function(){var a=g.iE(),b=e4(this);b=b?b.Ef:this.Ef;a&&b&&g.AE(a,[b])};
g.k.H$=function(){var a=g.iE(),b=e4(this);b=b?b.Ef:this.Ef;a&&b&&g.BE(a,[b])};
g.k.e5=function(){var a=e4(this);h4(this.context.logger,a.jj.E2);var b=g.iE();if(b&&a)if(this.J.L("web_infocards_teaser_show_logging_fix")){var c=[];a.Pj&&c.push(a.Pj);a.Ef&&c.push(a.Ef);c.length>0&&g.AE(b,c)}else g.AE(b,[a.Pj,a.Ef])};
g.k.J$=function(){var a=g.iE(),b=e4(this);a&&b&&g.BE(a,[b.Pj])};
g.k.d5=function(a){var b=e4(this),c=g.iE();this.j?a?(a=this.context.logger,h4(a,b.jj.sM),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Pj&&g.CE(c,b.Pj)):(a=this.context.logger,h4(a,b.jj.sM),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Ef&&g.CE(c,b.Ef)):(a=this.context.logger,h4(a,b.jj.sM),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.Ef&&g.CE(c,this.Ef))};g.x(f4,W3);f4.prototype.qH=function(){W3.prototype.qH.call(this);Irb(this)};
f4.prototype.show=function(){W3.prototype.show.call(this);var a=g.iE(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.AE(a,[g.gE(b.itct)])};
f4.prototype.hide=function(){W3.prototype.hide.call(this);var a=g.iE(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.BE(a,[g.gE(b.itct)])};g.x(g4,f4);
g4.prototype.wy=function(){g.Jv(this.Jb(),"iv-branding");var a=this.annotation.data;this.B=this.createElement({I:"img",La:["branding-img","iv-click-target"],W:{"aria-label":"Marca-d'\u00e1gua do canal",src:a.image_url,width:a.image_width,height:a.image_height}});g.Zs(this.B,!1);var b=this.createElement({I:"button",La:["branding-img-container","ytp-button"]});b.appendChild(this.B);this.Jb().appendChild(b);var c=this.annotation.Ee();c&&X3(this,b,c,this.annotation.id,a.session_data);this.context.J.L("disable_branding_context")||Mrb(this,
a)};
g4.prototype.show=function(){if(!this.isActive&&(f4.prototype.show.call(this),this.N||(this.wy(),this.N=!0),g.Zs(this.Jb(),!0),this.isActive=!0,this.B)){try{Jrb(this,this.B)}catch(a){}g.Jv(this.context.J.getRootNode(),"ytp-branding-shown")}};
g4.prototype.hide=function(){this.isActive&&(f4.prototype.hide.call(this),g.Zs(this.Jb(),!1),this.isActive=!1,g.Lv(this.context.J.getRootNode(),"ytp-branding-shown"))};
g4.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);f4.prototype.destroy.call(this)};g.x(Orb,f4);g.k=Orb.prototype;
g.k.wy=function(){var a=this,b=this.annotation.data;if(this.annotation.style==="cta")var c=6;else if(this.annotation.style==="video"||this.annotation.style==="playlist")c=7;this.K=b.collapsedelay_ms||this.K;var d=["iv-promo","iv-promo-inactive"];this.Jb().setAttribute("aria-hidden","true");this.Jb().setAttribute("aria-label","Promo\u00e7\u00e3o");this.Jb().tabIndex=0;var e=this.annotation.Ee(),f=b.image_url;if(f){var h=this.createElement({I:"div",La:["iv-promo-img","iv-click-target"]});f=this.createElement({I:"img",
W:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?(f=this.createElement({I:"span",S:"iv-promo-video-duration",xa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=this.createElement({I:"span",S:"iv-promo-playlist-length",xa:b.playlist_length.toString()}),h.appendChild(f));e&&X3(this,h,e,this.annotation.id,b.session_data,void 0,c)}e?(f=this.createElement({I:"a",S:"iv-promo-txt"}),g.Oe(f,R3(e)),this.j=f):this.j=this.createElement({I:"div",S:"iv-promo-txt"});switch(this.annotation.style){case "cta":case "website":var l=
this.createElement({I:"p",V:[{I:"strong",xa:b.text_line_1}]});var m=this.createElement({I:"p",V:[{I:"span",S:"iv-promo-link",xa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=this.createElement({I:"button",La:["iv-promo-round-expand-icon","ytp-button"]});f=this.createElement({I:"button",La:["iv-button","iv-promo-button"],V:[{I:"span",S:"iv-button-content",xa:f}]});var p=this.createElement({I:"div",S:"iv-promo-button-container"});p.appendChild(f);e&&X3(this,
this.Jb(),e,this.annotation.id,b.session_data,void 0,c)}g.Jv(this.j,"iv-click-target");e&&X3(this,this.j,e,this.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=this.createElement({I:"p",V:[{I:"span",xa:b.text_line_1}]}),m=this.createElement({I:"p",V:[{I:"strong",xa:b.text_line_2}]}),b.is_live&&(l=m,m=this.createElement({I:"span",La:["yt-badge","iv-promo-badge-live"],xa:"AO VIVO AGORA"})),g.Jv(this.j,"iv-click-target"),e&&X3(this,this.j,e,this.annotation.id,b.session_data,
void 0,c),d.push("iv-promo-video")}l&&this.j.appendChild(l);m&&this.j.appendChild(m);this.N.appendChild(this.j);p&&this.N.appendChild(p);c=this.createElement({I:"div",S:"iv-promo-actions"});this.B=this.createElement({I:"button",La:["iv-promo-expand","ytp-button"]});this.B.title="Expandir";this.context.j.listen(this.B,"click",function(q){Rrb(a,5E3,q)});
c.appendChild(this.B);g.Zs(this.B,!1);this.context.j.listen(this.Jb(),"mouseover",this.G9,this);this.context.j.listen(this.Jb(),"mouseout",this.F9,this);this.context.j.listen(this.Jb(),"touchend",function(q){Rrb(a,5E3,q)});
this.C=this.createElement({I:"button",La:["iv-promo-close","ytp-button"]});this.C.title="Fechar";this.context.j.listen(this.C,"click",this.annotation.style==="cta"&&b.text_line_3?this.B9:this.A9,this);c.appendChild(this.C);g.Kv(this.Jb(),d);h&&(g.Ff(this.Jb(),h),n&&h.appendChild(n));g.Ff(this.Jb(),this.N);g.Ff(this.Jb(),c)};
g.k.show=function(){this.isActive||(f4.prototype.show.call(this),this.Y||(this.wy(),this.Y=!0),g.Zs(this.Jb(),!0),g.ng(function(){g.Lv(this.Jb(),"iv-promo-inactive")},100,this),this.Jb().removeAttribute("aria-hidden"),this.isActive=!0,Trb(this),Prb(this),Qrb(this,this.K))};
g.k.hide=function(){this.isActive&&(g.Jv(this.Jb(),"iv-promo-inactive"),this.isActive=!1,this.Jb().setAttribute("aria-hidden","true"))};
g.k.YM=function(a,b,c,d,e,f){return this.isCollapsed?!1:f4.prototype.YM.call(this,a,b,c,d,e,f)};
g.k.G9=function(a){this.Z=!0;Rrb(this,500,a)};
g.k.F9=function(){this.Z=!1;Srb(this)};
g.k.A9=function(a){a.stopPropagation();this.hide()};
g.k.B9=function(a){a.stopPropagation();Trb(this);this.isCollapsed=!0;g.Jv(this.Jb(),"iv-promo-collapsed-no-delay");this.G.start()};
g.k.destroy=function(){this.G.dispose();f4.prototype.destroy.call(this)};g.x(Vrb,g.fV);g.k=Vrb.prototype;g.k.Th=function(a,b){if(!jsb(this.player.U().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.$1(b))&&$rb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(yrb(this.j,b),B3(this.player)),!0}return null};
g.k.getOptions=function(){return jsb(this.player.U().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.bv=function(){var a=this.player.U(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return g.iT(b)||g.sT(this.player.app)?!1:c===1&&!b.FY||a.Oa.get(b.videoId)||g.$S(b)||g.bYa(b)?!0:!1};
g.k.kL=function(){if(this.C){var a=this.player.qb().getVideoContentRect(!0);g.Xs(this.C.element,a.width,a.height);g.Ts(this.C.element,a.left,a.top)}if(this.j){var b=this.player.Un();a=this.j;b=b.width;g.Nv(a.D,"iv-drawer-small",b<=426);g.Nv(a.D,"iv-drawer-big",b>=1280)}};
g.k.f5=function(a){Xrb(this,a.state);g.xF(a.state,2)&&(this.Xk()&&this.Cp()&&this.player.getPresentingPlayerType()!==2&&this.iC(!1),this.hC(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.zA(h)&&h.responseXML?h.responseXML:null)&&($rb(b,h),g.Jv(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.fV.prototype.load.call(this);Xrb(this,this.player.getPlayerStateObject());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.QB()&&(a=asb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.U().Oa.get(d);f&&bsb(e,f);f=f&&(f.sO||f.OI);if(!c.Kv||f)c.Xa?Yrb(this,c.Xa,e):(this.N=function(){if(!b.Z)b.onVideoDataChange(e);var h=b.player.getVideoData();(h==null?0:g.ZS(h))&&!b.ra&&fsb(b,h)},this.player.addEventListener("videodatachange",this.N));
g.GT(this.player,this.C.element,4);this.kL();(f=g.$S(c))&&esb(this,f);(f=g.bYa(c))&&f.featuredChannel&&isb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.Yg=g.wf("ytp-cards-button",this.player.getRootNode());g.ZS(c)&&fsb(this,c)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Xa&&Yrb(this,b.Xa,a)};
g.k.unload=function(){this.player.qf("annotations_module");for(var a=g.v(Object.keys(this.K)),b=a.next();!b.done;b=a.next())this.K[b.value].destroy();this.Y=null;this.j&&(this.j.destroy(),this.j=null,B3(this.player));this.Z=!1;this.G&&(this.G.abort(),this.G=null);this.ra=!1;this.K={};this.B.hide();g.fV.prototype.unload.call(this);this.C.detach();this.N&&(this.player.removeEventListener("videodatachange",this.N),this.N=null)};
g.k.w0=function(a){a===this.player.getVideoData().videoId&&(this.loaded?csb(this):this.load())};
g.k.Xk=function(){var a;return((a=this.j)==null?void 0:a.isAvailable())||this.ra};
g.k.Cp=function(){return!!this.j&&this.j.C};
g.k.iC=function(a,b,c){b=b===void 0?!1:b;this.Xk();this.j&&(a?c?Z3(this.j,c,b):Z3(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):$3(this.j))};
g.k.hC=function(a,b){this.player.publish(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.ya=function(){this.player.U().Oa.unsubscribe("vast_info_card_add",this.w0,this);g.Lv(this.player.getRootNode(),g.zY.IV_DRAWER_OPEN);for(var a=this.va,b=g.yv,c=0,d=a.length;c<d;c++)b.Wj(a[c]);this.va.length=0;g.fV.prototype.ya.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.M(this,a);return a.element};g.eV("annotations_module",Vrb);g.eV("creatorendscreen",Rqb);})(_yt_player);
