Algoritmo "Exer-90"
//
Var
valor1, valor2: inteiro

Procedimento somador(a, b: inteiro)
inicio
   escreval ("A soma entre os valores é: ", a + b)
fimProcedimento
Inicio
   escreval ("PROCEDIMENTOS - SOMADOR")
   escreval ()
   escreval ("Vamos calcular a somar de dois valores: ")
   escreval ()
   escreva ("Digite o primeiro valor: ")
   leia (valor1)
   escreva ("Digite o segundo valor: ")
   leia (valor2)
   
   somador(valor1, valor2)

Fimalgoritmo