Algoritmo "funcionario"
//  
//  
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/5/2024
Var
Nome:Caractere
Salario:Caractere

Inicio
Escreva(" Nome do funcionário: ")
leia(Nome)
Escreva("Salário: ")
leia(Salario)
Escreva("O funcionario ",Nome )
Escreva(" ganhou em junho " ,Salario)
Escreva(",00")

Fimalgoritmo