algoritmo "login_de_cadastro"
var
   Nome, Senha, Usuario: Caractere
inicio
      Escreva("Digite seu nome: ")
      Leia(Nome)
      Escreval("Muito Prazer, ", Nome, "!")
      Escreval("Realize seu cadastro")
      Escreva("Digite um nome de usuario: ")
      Leia(Usuario)
      Escreva("Digite uma senha válida: ")
      Leia(Senha)
      Escreval("Login feito com sucesso")
      Escreva("Bem Vindo(a), ", Usuario, "!")
fimalgoritmo