algoritmo "exercicio_90"
var

   A, B: inteiro

// procedimentos

Procedimento pulaLinha()
inicio

      Escreval("")

FimProcedimento


Procedimento somador(X, Y: inteiro)
inicio

      Escreval("A SOMA ENTRE ELES É", X + Y)

FimProcedimento

inicio

      Escreva("DIGITE UM NÚMERO: ")
      Leia(A)
      
      Escreva("DIGITE UM NÚMERO: ")
      Leia(B)
      
      pulaLinha()
      somador(A, B)


fimalgoritmo