Algoritmo "09.3-repetições"

Var
  valor,valor2, salto, contador: inteiro

Inicio
      contador <- 0
      escreva ("Quer ir até que valor?")
      leia (valor)
      escreva ("Qual valor do salto? ")
      leia (salto)

      enquanto  (contador <=valor) faca
                escreval (contador)
                contador <- (contador + salto)
      fimenquanto

      escreval ("Acabou!")


Fimalgoritmo