algoritmo "semnome"
var
contador,escolher:inteiro

inicio
Escreval("BEM VINDO AO CONTADOR!")
Escreval("=======================")
Escreval("aperte 1 para prosseguir!")
Leia(escolher)

escolha escolher
   caso 1
      contador<-0
      Enquanto (contador<=18)faca
         Escreva(contador)
         contador<-contador + 3
      fimenquanto
outrocaso
Escreva("desculpe não identificamos!")
fimescolha

fimalgoritmo
