algoritmo "semnome"
var
contador,selecionador:inteiro
inicio
Escreval("OLA BEM VINDO AO CONTADOR!")
Escreval("============================")
Escreval("Escreva um número inteirou ou positivo qualquer para contar!")
Leia(selecionador)
Escreval("=============================================================")

contador<-0

enquanto (contador<=selecionador)faca
   Escreval(contador)
   contador<- contador + 1
fimenquanto


fimalgoritmo
