algoritmo "semnome"
var
contador:inteiro
inicio
Escreval("BEM VINDO AO CONTADOR!")
Escreval("=======================")
Escreval("iremos mostrar os números divisiveis por 4!")
Escreval("===========================================")

contador <- 30

enquanto (contador >= 1) faca
   Escreval(contador)
   contador <- contador - 1
   se (contador% 4 = 0) entao
   Escreval("[",contador,"]")

contador <- contador - 1
fimse



fimenquanto



fimalgoritmo
