algoritmo "56"
var
soma,N,contador:inteiro
inicio
Escreval("BEM-VINDO AO SOMATÓRIO!")
Escreval("========================")

contador <- 1
enquanto (soma <> 1111) faca
   Escreva("digite um numero:")
   Leia(N)
   soma <- soma + N
   contador <- contador + 1
   
se (N = 1111) entao
   Escreval("você usou o comando de desligue!")
   soma <- soma - 1111
   Escreval("sua soma foi de ",soma)
   
   
   
fimalgoritmo

fimse
fimenquanto

